routes/web.php
    $videos_education = DB::Table('videos')->select('videos.*')
    ->join('sub_topics', 'sub_topics.id','videos.subtopic_id')
    ->join('users','users.id','videos.user_id')
    ->where('mainTopic_id', 6)
    ->where('videos.sistas', 0)
    ->whereNull('videos.deleted_at')
    ->get();

    return view('flow',compact('subtopics','channel','videos_haltcare','videos_life','videos_health','videos_business','videos_environnement','videos_education'));

})->name('flow')->middleware('auth');

// kids page : apercu
Route::get('/sistas', function () {
    $subtopics = DB::Table('sub_topics')->select('*')
    ->get();

    $videos_haltcare = DB::Table('videos')->select('videos.*')
                                 ->join('sub_topics', 'sub_topics.id','videos.subtopic_id')
                                 ->join('users','users.id','videos.user_id')
                                 ->where('users.age','<',15)
                                 ->where('videos.sistas', 1)
                                 ->where('mainTopic_id', 1)
                                 ->whereNull('videos.deleted_at')
                                 ->get();

    $videos_life = DB::Table('videos')->select('videos.*')
    ->join('sub_topics', 'sub_topics.id','videos.subtopic_id')
    ->join('users','users.id','videos.user_id')
    ->where('users.age','<',15)
    ->where('videos.sistas', 1)
    ->where('mainTopic_id', 2)
    ->whereNull('videos.deleted_at')
    ->get();

    $videos_health = DB::Table('videos')->select('videos.*')
    ->join('sub_topics', 'sub_topics.id','videos.subtopic_id')
    ->join('users','users.id','videos.user_id')
    ->where('users.age','<',15)
    ->where('videos.sistas', 1)
    ->where('mainTopic_id', 3)
    ->whereNull('videos.deleted_at')
    ->get();


    $videos_business = DB::Table('videos')->select('videos.*')
    ->join('sub_topics', 'sub_topics.id','videos.subtopic_id')
    ->join('users','users.id','videos.user_id')
    ->where('users.age','<',15)
    ->where('videos.sistas', 1)
    ->where('mainTopic_id', 4)
    ->whereNull('videos.deleted_at')
    ->get();

    $videos_environnement = DB::Table('videos')->select('videos.*')
    ->join('sub_topics', 'sub_topics.id','videos.subtopic_id')
    ->join('users','users.id','videos.user_id')
    ->where('users.age','<',15)
    ->where('videos.sistas', 1)
    ->where('mainTopic_id', 5)
    ->whereNull('videos.deleted_at')
    ->get();

    $videos_education = DB::Table('videos')->select('videos.*')
    ->join('sub_topics', 'sub_topics.id','videos.subtopic_id')
    ->join('users','users.id','videos.user_id')
    ->where('users.age','<',15)
    ->where('videos.sistas', 1)
    ->where('mainTopic_id', 6)
    ->whereNull('videos.deleted_at')
    ->get();

    return view('flow',compact('subtopics','videos_haltcare','videos_life','videos_health','videos_business','videos_environnement','videos_education'));
})->name('sistas')->middleware('auth');

Auth::routes();

Route::resource('users', 'UserController')->middleware('auth');

Route::get('suscribe/{channel_id}','UserController@suscribe')->name('suscribe');

Route::resource('profiles', 'ProfileController')->middleware('auth');

Route::resource('channels', 'channelController')->middleware('auth');

Route::resource('categorySecondaries', 'CategorySecondaryController')->middleware('auth');

Route::resource('categoryPrimaries', 'CategoryPrimaryController')->middleware('auth');

Route::resource('subTopics', 'SubTopicController')->middleware('auth');

Route::resource('mainTopics', 'MainTopicController')->middleware('auth');

Route::resource('videos', 'VideoController')->middleware('auth');
Route::get('likevideo/{video_id}','VideoController@likeVideo')->name('likevideo')->middleware('auth');
Route::get('dislikevideo/{video_id}','VideoController@dislikeVideo')->name('dislikevideo')->middleware('auth');


Route::resource('reports', 'ReportController');

Route::resource('shares', 'ShareController');

Route::resource('reads', 'ReadController');

Route::resource('comments', 'CommentController');
Route::get('comment/likecomment/{comment_id}','CommentController@likeComment')->name('likecomment');
Route::get('comment/dislikecomment/{comment_id}','CommentController@dislikeComment')->name('dislikecomment');

Route::resource('responseComments', 'ResponseCommentController');


Route::resource('events', 'EventController');

Route::resource('activities', 'ActivityController');

Route::resource('contacts', 'ContactController');

Route::resource('products', 'productController');

Route::view('timeShield', 'time');
Route::view('flow2', 'flow2');

Route::view('profil-management', 'profil-management');

Route::view('monFlow2', 'monFlow2');


Route::view('/chaineAbonne', 'chaineAbonne');

Route::get('/notification', function(){
    $channel = DB::Table('users')->select('channels.*')
    ->join('channels', 'users.id', 'channels.user_id')
    ->where('users.id', Auth::id())
    ->first();

    $follows = DB::table('abonne_channel')
    ->select('channels.*')
    ->join('channels','channels.id','abonne_channel.channel_id')
    ->where('abonne_channel.user_id', Auth::id())
    ->get();

    $_COOKIE['state'] = "home";

    return view('notification',compact('channel','follows'));
})->name('notification');

Route::get('/parametre', function () {
    $channel = DB::Table('users')->select('channels.*')
    ->join('channels', 'users.id', 'channels.user_id')
    ->where('users.id', Auth::id())
    ->first();
    
        $_COOKIE['state'] = "parameter";

    return view('users.parametre',compact('channel'));

})->name('parametre')->middleware('auth');

Route::get('/parametrePhoto', function () {
    $channel = DB::Table('users')->select('channels.*')
    ->join('channels', 'users.id', 'channels.user_id')
    ->where('users.id', Auth::id())
    ->first();
    return view('users.parametrePhoto',compact('channel'));
})->name('user.pictures')->middleware('auth');


Route::post('/parameter', [App\Http\Controllers\UserController::class, 'parameter'])->name('users.parameter')->middleware('auth');

Route::get('/picture/{alpha}', [App\Http\Controllers\UserController::class, 'picture'])->name('users.picture')->middleware('auth');

Route::get('/language', function(){
    return view('language');
})->name('language.show');

Route::get('/language/{lang}', [App\Http\Controllers\UserController::class, 'choose_language'])->name('language.choose');

Route::get('/playlist/{video}', [App\Http\Controllers\PlaylistController::class, 'add'])->name('playlist.add');

Route::get('/playlist/delete/{video}', [App\Http\Controllers\PlaylistController::class, 'remove'])->name('playlist.remove');

Route::resource('playlists', 'PlaylistController');

Route::get('/process', function(){

    $gateway = new Braintree\Gateway([
        'environment' => 'sandbox',
        'merchantId' => '2yw4qvsvxcr5fhyx',
        'publicKey' => 'j2cqsvvdjnvs2v5w',
        'privateKey' => '9605f4859f57d23d0ee40cedb88c834e'
        ]);

    $clientToken = $gateway->clientToken()->generate();

    $channel = DB::Table('users')->select('channels.*')
    ->join('channels', 'users.id', 'channels.user_id')
    ->where('users.id', Auth::id())
    ->first();
    return view('process',compact('channel','clientToken'));
})->name('process');

Route::post('/process', function(){

    //setting up braintree credentials.
    Braintree_Configuration::environment('sandbox');
    Braintree_Configuration::merchantId('2yw4qvsvxcr5fhyx');
    Braintree_Configuration::publicKey('j2cqsvvdjnvs2v5w');
    Braintree_Configuration::privateKey('9605f4859f57d23d0ee40cedb88c834e');

    $result = Braintree_Transaction::sale([
        'amount' => $_POST['amount'],
        'customer' => ['firstName' => Auth::user()->name],
        'paymentMethodNonce' => $_POST['payment_method_nonce'],
        'options' => [
            'submitForSettlement' => True
        ]
        ]);

    if ($result->success === true) {
        $facturation = DB::table('facturations')
        ->select('facturations.*')
        ->join('users', 'users.id', 'facturations.user_id')
        ->where('users.id', Auth::id() )
        ->orderByDesc('facturations.created_at')
        ->first();

        $start =  new \Datetime();
        if($_POST['amount'] > 0)
            if($_POST['amount'] == 100 || $_POST['amount'] == 50 ){
                $type = "Annually";
                if($_POST['amount'] == 100 ){
                    $profile = "OUMMATI";
                    DB::table('users')
                    ->where('users.id',Auth::id())
                    ->update(['type'=> $profile]);
                }else{
                    $profile = "SAHABA";
                    DB::table('users')
                    ->where('users.id',Auth::id())
                    ->update(['type'=> $profile]);}
            }
            else{
                $type = "Monthly";
                if($_POST['amount'] == 10 ){
                    $profile = "OUMMATI";
                    DB::table('users')
                    ->where('users.id',Auth::id())
                    ->update(['type'=> $profile]);}
                else{
                    $profile = "SAHABA";
                    DB::table('users')
                    ->where('users.id',Auth::id())
                    ->update(['type'=> $profile]);}
            }

        if(!$facturation){
            $end =  new \Datetime();
            if($type == "Monthly")
                $end->add(new DateInterval('P1M'));
            else
                $end->add(new DateInterval('P12M'));
        }else{
            $end_at = new \Datetime($facturation->end_at);
            if($type == "Monthly")
                $end = $end_at->add(new DateInterval('P1M'));
            else
                $end = $end_at->add(new DateInterval('P12M'));
        }

        DB::table('facturations')->insert([
            'amount' =>  $_POST['amount'],
            'type' => $type,
            'profile' => $profile,
            'user_id' => Auth::id(),

app/Models/CategoryPrimary.php
<?php

namespace App\Models;

use Eloquent as Model;
use Illuminate\Database\Eloquent\SoftDeletes;
use Channel;

/**
 * Class CategoryPrimary
 * @package App\Models
 * @version January 25, 2021, 10:45 pm UTC
 *
 * @property string libelle
 */
class CategoryPrimary extends Model
{

    public $table = 'category_primaries';

    public $fillable = [
        'libelle'
    ];

    /**
     * The attributes that should be casted to native types.
     *
     * @var array
     */
    protected $casts = [
        'id' => 'integer',
        'libelle' => 'string'
    ];

    /**
     * Validation rules
     *
     * @var array
     */
    public static $rules = [
        'libelle' => 'required'
    ];

    public function channels()
    {
        return $this->hasMany(Channel::class);
    }
    
}

app/Http/Controllers/CategoryPrimaryController.php
<?php

namespace App\Http\Controllers;

use App\Http\Requests\CreateCategoryPrimaryRequest;
use App\Http\Requests\UpdateCategoryPrimaryRequest;
use App\Http\Controllers\AppBaseController;
use App\Models\CategoryPrimary;
use Illuminate\Http\Request;
use Flash;
use Response;

class CategoryPrimaryController extends AppBaseController
{
    /**
     * Display a listing of the CategoryPrimary.
     *
     * @param Request $request
     *
     * @return Response
     */
    public function index(Request $request)
    {
        /** @var CategoryPrimary $categoryPrimaries */
        $categoryPrimaries = CategoryPrimary::all();

        return view('category_primaries.index')
            ->with('categoryPrimaries', $categoryPrimaries);
    }

    /**
     * Show the form for creating a new CategoryPrimary.
     *
     * @return Response
     */
    public function create()
    {
        return view('category_primaries.create');
    }

    /**
     * Store a newly created CategoryPrimary in storage.
     *
     * @param CreateCategoryPrimaryRequest $request
     *
     * @return Response
     */
    public function store(CreateCategoryPrimaryRequest $request)
    {
        $input = $request->all();

        /** @var CategoryPrimary $categoryPrimary */
        $categoryPrimary = CategoryPrimary::create($input);

        Flash::success('Category Primary saved successfully.');

        return redirect(route('categoryPrimaries.index'));
    }

    /**
     * Display the specified CategoryPrimary.
     *
     * @param int $id
     *
     * @return Response
     */
    public function show($id)
    {
        /** @var CategoryPrimary $categoryPrimary */
        $categoryPrimary = CategoryPrimary::find($id);

        if (empty($categoryPrimary)) {
            Flash::error('Category Primary not found');

            return redirect(route('categoryPrimaries.index'));
        }

        return view('category_primaries.show')->with('categoryPrimary', $categoryPrimary);
    }

    /**
     * Show the form for editing the specified CategoryPrimary.
     *
     * @param int $id
     *
     * @return Response
     */
    public function edit($id)
    {
        /** @var CategoryPrimary $categoryPrimary */
        $categoryPrimary = CategoryPrimary::find($id);

        if (empty($categoryPrimary)) {
            Flash::error('Category Primary not found');

            return redirect(route('categoryPrimaries.index'));
        }

        return view('category_primaries.edit')->with('categoryPrimary', $categoryPrimary);
    }

    /**
     * Update the specified CategoryPrimary in storage.
     *
     * @param int $id
     * @param UpdateCategoryPrimaryRequest $request
     *
     * @return Response
     */
    public function update($id, UpdateCategoryPrimaryRequest $request)
    {
        /** @var CategoryPrimary $categoryPrimary */
        $categoryPrimary = CategoryPrimary::find($id);

        if (empty($categoryPrimary)) {
            Flash::error('Category Primary not found');

            return redirect(route('categoryPrimaries.index'));
        }

        $categoryPrimary->fill($request->all());
        $categoryPrimary->save();

        Flash::success('Category Primary updated successfully.');

        return redirect(route('categoryPrimaries.index'));
    }

    /**
     * Remove the specified CategoryPrimary from storage.
     *
     * @param int $id
     *
     * @throws \Exception
     *
     * @return Response
     */
    public function destroy($id)
    {
        /** @var CategoryPrimary $categoryPrimary */
        $categoryPrimary = CategoryPrimary::find($id);

        if (empty($categoryPrimary)) {
            Flash::error('Category Primary not found');

            return redirect(route('categoryPrimaries.index'));
        }

        $categoryPrimary->delete();

        Flash::success('Category Primary deleted successfully.');

        return redirect(route('categoryPrimaries.index'));
    }
}

resources/views/category_primaries/create.blade.php
@extends('layouts.app')

@section('content')
    <section class="content-header">
        <h1>
            Category Primary
        </h1>
    </section>
    <div class="content">
        @include('adminlte-templates::common.errors')
        <div class="box box-primary">
            <div class="box-body">
                <div class="row">
                    {!! Form::open(['route' => 'categoryPrimaries.store']) !!}

                        @include('category_primaries.fields')

                    {!! Form::close() !!}
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/category_primaries/edit.blade.php
@extends('layouts.app')

@section('content')
    <section class="content-header">
        <h1>
            Category Primary
        </h1>
   </section>
   <div class="content">
       @include('adminlte-templates::common.errors')
       <div class="box box-primary">
           <div class="box-body">
               <div class="row">
                   {!! Form::model($categoryPrimary, ['route' => ['categoryPrimaries.update', $categoryPrimary->id], 'method' => 'patch']) !!}

                        @include('category_primaries.fields')

                   {!! Form::close() !!}
               </div>
           </div>
       </div>
   </div>
@endsection

resources/views/category_primaries/fields.blade.php
<!-- Libelle Field -->
<div class="form-group col-sm-6">
    {!! Form::label('libelle', 'Libelle:') !!}
    {!! Form::text('libelle', null, ['class' => 'form-control']) !!}
</div>

<!-- Submit Field -->
<div class="form-group col-sm-12">
    {!! Form::submit('Save', ['class' => 'btn btn-primary']) !!}
    <a href="{{ route('categoryPrimaries.index') }}" class="btn btn-default">Cancel</a>
</div>

resources/views/category_primaries/index.blade.php
@extends('layouts.app')

@section('content')
    <section class="content-header">
        <h1 class="pull-left">Category Primaries</h1>
        <h1 class="pull-right">
           <a class="btn btn-primary pull-right" style="margin-top: -10px;margin-bottom: 5px" href="{{ route('categoryPrimaries.create') }}">Add New</a>
        </h1>
    </section>
    <div class="content">
        <div class="clearfix"></div>

        @include('flash::message')

        <div class="clearfix"></div>
        <div class="box box-primary">
            <div class="box-body">
                    @include('category_primaries.table')
            </div>
        </div>
        <div class="text-center">
        
        </div>
    </div>
@endsection

resources/views/category_primaries/show.blade.php
@extends('layouts.app')

@section('content')
    <section class="content-header">
        <h1>
            Category Primary
        </h1>
    </section>
    <div class="content">
        <div class="box box-primary">
            <div class="box-body">
                <div class="row" style="padding-left: 20px">
                    @include('category_primaries.show_fields')
                    <a href="{{ route('categoryPrimaries.index') }}" class="btn btn-default">Back</a>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/category_primaries/show_fields.blade.php
<!-- Id Field -->
<div class="form-group">
    {!! Form::label('id', 'Id:') !!}
    <p>{{ $categoryPrimary->id }}</p>
</div>

<!-- Libelle Field -->
<div class="form-group">
    {!! Form::label('libelle', 'Libelle:') !!}
    <p>{{ $categoryPrimary->libelle }}</p>
</div>

<!-- Created At Field -->
<div class="form-group">
    {!! Form::label('created_at', 'Created At:') !!}
    <p>{{ $categoryPrimary->created_at }}</p>
</div>

<!-- Updated At Field -->
<div class="form-group">
    {!! Form::label('updated_at', 'Updated At:') !!}
    <p>{{ $categoryPrimary->updated_at }}</p>
</div>

resources/views/category_primaries/table.blade.php
<div class="table-responsive">
    <table class="table" id="categoryPrimaries-table">
        <thead>
            <tr>
                <th>Libelle</th>
                <th colspan="3">Action</th>
            </tr>
        </thead>
        <tbody>
        @foreach($categoryPrimaries as $categoryPrimary)
            <tr>
                <td>{{ $categoryPrimary->libelle }}</td>
                <td>
                    {!! Form::open(['route' => ['categoryPrimaries.destroy', $categoryPrimary->id], 'method' => 'delete']) !!}
                    <div class='btn-group'>
                        <a href="{{ route('categoryPrimaries.show', [$categoryPrimary->id]) }}" class='btn btn-default btn-xs'><i class="glyphicon glyphicon-eye-open"></i></a>
                        <a href="{{ route('categoryPrimaries.edit', [$categoryPrimary->id]) }}" class='btn btn-default btn-xs'><i class="glyphicon glyphicon-edit"></i></a>
                        {!! Form::button('<i class="glyphicon glyphicon-trash"></i>', ['type' => 'submit', 'class' => 'btn btn-danger btn-xs', 'onclick' => "return confirm('Are you sure?')"]) !!}
                    </div>
                    {!! Form::close() !!}
                </td>
            </tr>
        @endforeach
        </tbody>
    </table>
</div>