routes/web.php
                                 ->where('videos.sistas', 1)
                                 ->where('mainTopic_id', 1)
                                 ->whereNull('videos.deleted_at')
                                 ->get();

    $videos_life = DB::Table('videos')->select('videos.*')
    ->join('sub_topics', 'sub_topics.id','videos.subtopic_id')
    ->join('users','users.id','videos.user_id')
    ->where('users.age','<',15)
    ->where('videos.sistas', 1)
    ->where('mainTopic_id', 2)
    ->whereNull('videos.deleted_at')
    ->get();

    $videos_health = DB::Table('videos')->select('videos.*')
    ->join('sub_topics', 'sub_topics.id','videos.subtopic_id')
    ->join('users','users.id','videos.user_id')
    ->where('users.age','<',15)
    ->where('videos.sistas', 1)
    ->where('mainTopic_id', 3)
    ->whereNull('videos.deleted_at')
    ->get();


    $videos_business = DB::Table('videos')->select('videos.*')
    ->join('sub_topics', 'sub_topics.id','videos.subtopic_id')
    ->join('users','users.id','videos.user_id')
    ->where('users.age','<',15)
    ->where('videos.sistas', 1)
    ->where('mainTopic_id', 4)
    ->whereNull('videos.deleted_at')
    ->get();

    $videos_environnement = DB::Table('videos')->select('videos.*')
    ->join('sub_topics', 'sub_topics.id','videos.subtopic_id')
    ->join('users','users.id','videos.user_id')
    ->where('users.age','<',15)
    ->where('videos.sistas', 1)
    ->where('mainTopic_id', 5)
    ->whereNull('videos.deleted_at')
    ->get();

    $videos_education = DB::Table('videos')->select('videos.*')
    ->join('sub_topics', 'sub_topics.id','videos.subtopic_id')
    ->join('users','users.id','videos.user_id')
    ->where('users.age','<',15)
    ->where('videos.sistas', 1)
    ->where('mainTopic_id', 6)
    ->whereNull('videos.deleted_at')
    ->get();

    return view('flow',compact('subtopics','videos_haltcare','videos_life','videos_health','videos_business','videos_environnement','videos_education'));
})->name('sistas')->middleware('auth');

Auth::routes();

Route::resource('users', 'UserController')->middleware('auth');

Route::get('suscribe/{channel_id}','UserController@suscribe')->name('suscribe');

Route::resource('profiles', 'ProfileController')->middleware('auth');

Route::resource('channels', 'channelController')->middleware('auth');

Route::resource('categorySecondaries', 'CategorySecondaryController')->middleware('auth');

Route::resource('categoryPrimaries', 'CategoryPrimaryController')->middleware('auth');

Route::resource('subTopics', 'SubTopicController')->middleware('auth');

Route::resource('mainTopics', 'MainTopicController')->middleware('auth');

Route::resource('videos', 'VideoController')->middleware('auth');
Route::get('likevideo/{video_id}','VideoController@likeVideo')->name('likevideo')->middleware('auth');
Route::get('dislikevideo/{video_id}','VideoController@dislikeVideo')->name('dislikevideo')->middleware('auth');


Route::resource('reports', 'ReportController');

Route::resource('shares', 'ShareController');

Route::resource('reads', 'ReadController');

Route::resource('comments', 'CommentController');
Route::get('comment/likecomment/{comment_id}','CommentController@likeComment')->name('likecomment');
Route::get('comment/dislikecomment/{comment_id}','CommentController@dislikeComment')->name('dislikecomment');

Route::resource('responseComments', 'ResponseCommentController');


Route::resource('events', 'EventController');

Route::resource('activities', 'ActivityController');

Route::resource('contacts', 'ContactController');

Route::resource('products', 'productController');

Route::view('timeShield', 'time');
Route::view('flow2', 'flow2');

Route::view('profil-management', 'profil-management');

Route::view('monFlow2', 'monFlow2');


Route::view('/chaineAbonne', 'chaineAbonne');

Route::get('/notification', function(){
    $channel = DB::Table('users')->select('channels.*')
    ->join('channels', 'users.id', 'channels.user_id')
    ->where('users.id', Auth::id())
    ->first();

    $follows = DB::table('abonne_channel')
    ->select('channels.*')
    ->join('channels','channels.id','abonne_channel.channel_id')
    ->where('abonne_channel.user_id', Auth::id())
    ->get();

    $_COOKIE['state'] = "home";

    return view('notification',compact('channel','follows'));
})->name('notification');

Route::get('/parametre', function () {
    $channel = DB::Table('users')->select('channels.*')
    ->join('channels', 'users.id', 'channels.user_id')
    ->where('users.id', Auth::id())
    ->first();
    
        $_COOKIE['state'] = "parameter";

    return view('users.parametre',compact('channel'));

})->name('parametre')->middleware('auth');

Route::get('/parametrePhoto', function () {
    $channel = DB::Table('users')->select('channels.*')
    ->join('channels', 'users.id', 'channels.user_id')
    ->where('users.id', Auth::id())
    ->first();
    return view('users.parametrePhoto',compact('channel'));
})->name('user.pictures')->middleware('auth');


Route::post('/parameter', [App\Http\Controllers\UserController::class, 'parameter'])->name('users.parameter')->middleware('auth');

Route::get('/picture/{alpha}', [App\Http\Controllers\UserController::class, 'picture'])->name('users.picture')->middleware('auth');

Route::get('/language', function(){
    return view('language');
})->name('language.show');

Route::get('/language/{lang}', [App\Http\Controllers\UserController::class, 'choose_language'])->name('language.choose');

Route::get('/playlist/{video}', [App\Http\Controllers\PlaylistController::class, 'add'])->name('playlist.add');

Route::get('/playlist/delete/{video}', [App\Http\Controllers\PlaylistController::class, 'remove'])->name('playlist.remove');

Route::resource('playlists', 'PlaylistController');

Route::get('/process', function(){

    $gateway = new Braintree\Gateway([
        'environment' => 'sandbox',
        'merchantId' => '2yw4qvsvxcr5fhyx',
        'publicKey' => 'j2cqsvvdjnvs2v5w',
        'privateKey' => '9605f4859f57d23d0ee40cedb88c834e'
        ]);

    $clientToken = $gateway->clientToken()->generate();

    $channel = DB::Table('users')->select('channels.*')
    ->join('channels', 'users.id', 'channels.user_id')
    ->where('users.id', Auth::id())
    ->first();
    return view('process',compact('channel','clientToken'));
})->name('process');

Route::post('/process', function(){

    //setting up braintree credentials.
    Braintree_Configuration::environment('sandbox');
    Braintree_Configuration::merchantId('2yw4qvsvxcr5fhyx');
    Braintree_Configuration::publicKey('j2cqsvvdjnvs2v5w');
    Braintree_Configuration::privateKey('9605f4859f57d23d0ee40cedb88c834e');

    $result = Braintree_Transaction::sale([
        'amount' => $_POST['amount'],
        'customer' => ['firstName' => Auth::user()->name],
        'paymentMethodNonce' => $_POST['payment_method_nonce'],
        'options' => [
            'submitForSettlement' => True
        ]
        ]);

    if ($result->success === true) {
        $facturation = DB::table('facturations')
        ->select('facturations.*')
        ->join('users', 'users.id', 'facturations.user_id')
        ->where('users.id', Auth::id() )
        ->orderByDesc('facturations.created_at')
        ->first();

        $start =  new \Datetime();
        if($_POST['amount'] > 0)
            if($_POST['amount'] == 100 || $_POST['amount'] == 50 ){
                $type = "Annually";
                if($_POST['amount'] == 100 ){
                    $profile = "OUMMATI";
                    DB::table('users')
                    ->where('users.id',Auth::id())
                    ->update(['type'=> $profile]);
                }else{
                    $profile = "SAHABA";
                    DB::table('users')
                    ->where('users.id',Auth::id())
                    ->update(['type'=> $profile]);}
            }
            else{
                $type = "Monthly";
                if($_POST['amount'] == 10 ){
                    $profile = "OUMMATI";
                    DB::table('users')
                    ->where('users.id',Auth::id())
                    ->update(['type'=> $profile]);}
                else{
                    $profile = "SAHABA";
                    DB::table('users')
                    ->where('users.id',Auth::id())
                    ->update(['type'=> $profile]);}
            }

        if(!$facturation){
            $end =  new \Datetime();
            if($type == "Monthly")
                $end->add(new DateInterval('P1M'));
            else
                $end->add(new DateInterval('P12M'));
        }else{
            $end_at = new \Datetime($facturation->end_at);
            if($type == "Monthly")
                $end = $end_at->add(new DateInterval('P1M'));
            else
                $end = $end_at->add(new DateInterval('P12M'));
        }

        DB::table('facturations')->insert([
            'amount' =>  $_POST['amount'],
            'type' => $type,
            'profile' => $profile,
            'user_id' => Auth::id(),
            'end_at' => $end,
            'created_at' => now(),
            'updated_at' => now()
        ]);

        $start = $start->format("d.m.Y");
        $end = $end->format("d.m.Y");

        Auth::user()->notify(new App\Notifications\InvoiceNotify());

        Flash::success('Payment made successfully ! <br> ~ Valid from ' .$start.  " to " .$end. ".<br> <a href='"  .route('home'). "' class='btn btn-info'>Quitter et retourner à l'acceuil</a> ");

    }
    else
        Flash::error('Error occured &#x1F534; '.$result->errors->message );
        // var_dump($result) );

    return redirect(route('payment'));
})->name('payment');


Route::resource('facturations', 'FacturationController');

Route::get('/tarif', function(){
    $channel = DB::Table('users')->select('channels.*')
    ->join('channels', 'users.id', 'channels.user_id')
    ->where('users.id', Auth::id())
    ->first();

app/Models/ResponseComment.php
<?php

namespace App\Models;

use Eloquent as Model;
use Illuminate\Database\Eloquent\SoftDeletes;

/**
 * Class ResponseComment
 * @package App\Models
 * @version February 23, 2021, 7:51 pm UTC
 *
 * @property string response_value
 * @property unsignedInteger comment_id
 */
class ResponseComment extends Model
{
    use SoftDeletes;

    public $table = 'response_comments';
    

    protected $dates = ['deleted_at'];



    public $fillable = [
        'response_value',
        'user_id',
        'comment_id'
    ];

    /**
     * The attributes that should be casted to native types.
     *
     * @var array
     */
    protected $casts = [
        'id' => 'integer',
        'response_value' => 'string'
    ];

    /**
     * Validation rules
     *
     * @var array
     */
    public static $rules = [
        'response_value' => 'required',
        'comment_id' => 'required'
    ];

    
}

app/Http/Controllers/ResponseCommentController.php
<?php

namespace App\Http\Controllers;

use App\Http\Requests\CreateResponseCommentRequest;
use App\Http\Requests\UpdateResponseCommentRequest;
use App\Http\Controllers\AppBaseController;
use App\Models\ResponseComment;
use App\Models\Comment;
use Illuminate\Http\Request;
use Flash;
use Response;

use Auth;
use DB;

class ResponseCommentController extends AppBaseController
{
    /**
     * Display a listing of the ResponseComment.
     *
     * @param Request $request
     *
     * @return Response
     */
    public function index(Request $request)
    {
        /** @var ResponseComment $responseComments */
        $responseComments = ResponseComment::all();

        return view('response_comments.index')
            ->with('responseComments', $responseComments);
    }

    /**
     * Show the form for creating a new ResponseComment.
     *
     * @return Response
     */
    public function create()
    {
        return view('response_comments.create');
    }

    /**
     * Store a newly created ResponseComment in storage.
     *
     * @param CreateResponseCommentRequest $request
     *
     * @return Response
     */
    public function store(CreateResponseCommentRequest $request)
    {
        $input = $request->all();

        /** @var ResponseComment $responseComment */
        $responseComment = ResponseComment::create($input);

        Flash::success('Response Comment saved successfully.');

        return redirect(route('responseComments.index'));
    }

    public function contribute()
    {
        $input = ['response_value' => htmlspecialchars($_GET['response_value']), 'user_id' => Auth::id(), 'comment_id' => htmlspecialchars($_GET['comment_id'])];

        /** @var Comment $comment */
        $response = ResponseComment::create($input);

        Flash::success('Comment saved successfully.');

        $comments = DB::Table('comments')->select('users.*','comments.value' ,'comments.id as comment_id' ,'comments.created_at as created_at')
        ->join('videos', 'videos.id', 'comments.video_id')
        ->join('users', 'videos.user_id', 'users.id')
        ->where('comments.video_id',  htmlspecialchars($_GET['video_id']))
        ->get();

        $reads = DB::Table('reads')
        ->where('video_id', $_GET['video_id'])
        ->count();

        return view('play',compact('comments','reads'));
    }

    /**
     * Display the specified ResponseComment.
     *
     * @param int $id
     *
     * @return Response
     */
    public function show($id)
    {
        /** @var ResponseComment $responseComment */
        $responseComment = ResponseComment::find($id);

        if (empty($responseComment)) {
            Flash::error('Response Comment not found');

            return redirect(route('responseComments.index'));
        }

        return view('response_comments.show')->with('responseComment', $responseComment);
    }

    /**
     * Show the form for editing the specified ResponseComment.
     *
     * @param int $id
     *
     * @return Response
     */
    public function edit($id)
    {
        /** @var ResponseComment $responseComment */
        $responseComment = ResponseComment::find($id);

        if (empty($responseComment)) {
            Flash::error('Response Comment not found');

            return redirect(route('responseComments.index'));
        }

        return view('response_comments.edit')->with('responseComment', $responseComment);
    }

    /**
     * Update the specified ResponseComment in storage.
     *
     * @param int $id
     * @param UpdateResponseCommentRequest $request
     *
     * @return Response
     */
    public function update($id, UpdateResponseCommentRequest $request)
    {
        /** @var ResponseComment $responseComment */
        $responseComment = ResponseComment::find($id);

        if (empty($responseComment)) {
            Flash::error('Response Comment not found');

            return redirect(route('responseComments.index'));
        }

        $responseComment->fill($request->all());
        $responseComment->save();

        Flash::success('Response Comment updated successfully.');

        return redirect(route('responseComments.index'));
    }

    /**
     * Remove the specified ResponseComment from storage.
     *
     * @param int $id
     *
     * @throws \Exception
     *
     * @return Response
     */
    public function destroy($id)
    {
        /** @var ResponseComment $responseComment */
        $responseComment = ResponseComment::find($id);

        if (empty($responseComment)) {
            Flash::error('Response Comment not found');

            return redirect(route('responseComments.index'));
        }

        $responseComment->delete();

        Flash::success('Response Comment deleted successfully.');

        return redirect(route('responseComments.index'));
    }
}

resources/views/response_comments/create.blade.php
@extends('layouts.app')

@section('content')
    <section class="content-header">
        <h1>
            Response Comment
        </h1>
    </section>
    <div class="content">
        @include('adminlte-templates::common.errors')
        <div class="box box-primary">
            <div class="box-body">
                <div class="row">
                    {!! Form::open(['route' => 'responseComments.store']) !!}

                        @include('response_comments.fields')

                    {!! Form::close() !!}
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/response_comments/edit.blade.php
@extends('layouts.app')

@section('content')
    <section class="content-header">
        <h1>
            Response Comment
        </h1>
   </section>
   <div class="content">
       @include('adminlte-templates::common.errors')
       <div class="box box-primary">
           <div class="box-body">
               <div class="row">
                   {!! Form::model($responseComment, ['route' => ['responseComments.update', $responseComment->id], 'method' => 'patch']) !!}

                        @include('response_comments.fields')

                   {!! Form::close() !!}
               </div>
           </div>
       </div>
   </div>
@endsection

resources/views/response_comments/fields.blade.php
<!-- Response Value Field -->
<div class="form-group col-sm-6">
    {!! Form::label('response_value', 'Response Value:') !!}
    {!! Form::text('response_value', null, ['class' => 'form-control']) !!}
</div>

<!-- Submit Field -->
<div class="form-group col-sm-12">
    {!! Form::submit('Save', ['class' => 'btn btn-primary']) !!}
    <a href="{{ route('responseComments.index') }}" class="btn btn-default">Cancel</a>
</div>

resources/views/response_comments/index.blade.php
@extends('layouts.app')

@section('content')
    <section class="content-header">
        <h1 class="pull-left">Response Comments</h1>
        <h1 class="pull-right">
           <a class="btn btn-primary pull-right" style="margin-top: -10px;margin-bottom: 5px" href="{{ route('responseComments.create') }}">Add New</a>
        </h1>
    </section>
    <div class="content">
        <div class="clearfix"></div>

        @include('flash::message')

        <div class="clearfix"></div>
        <div class="box box-primary">
            <div class="box-body">
                    @include('response_comments.table')
            </div>
        </div>
        <div class="text-center">
        
        </div>
    </div>
@endsection

resources/views/response_comments/show.blade.php
@extends('layouts.app')

@section('content')
    <section class="content-header">
        <h1>
            Response Comment
        </h1>
    </section>
    <div class="content">
        <div class="box box-primary">
            <div class="box-body">
                <div class="row" style="padding-left: 20px">
                    @include('response_comments.show_fields')
                    <a href="{{ route('responseComments.index') }}" class="btn btn-default">Back</a>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/response_comments/show_fields.blade.php
<!-- Id Field -->
<div class="form-group">
    {!! Form::label('id', 'Id:') !!}
    <p>{{ $responseComment->id }}</p>
</div>

<!-- Response Value Field -->
<div class="form-group">
    {!! Form::label('response_value', 'Response Value:') !!}
    <p>{{ $responseComment->response_value }}</p>
</div>

<!-- Comment Id Field -->
<div class="form-group">
    {!! Form::label('comment_id', 'Comment Id:') !!}
    <p>{{ $responseComment->comment_id }}</p>
</div>

<!-- Created At Field -->
<div class="form-group">
    {!! Form::label('created_at', 'Created At:') !!}
    <p>{{ $responseComment->created_at }}</p>
</div>

<!-- Updated At Field -->
<div class="form-group">
    {!! Form::label('updated_at', 'Updated At:') !!}
    <p>{{ $responseComment->updated_at }}</p>
</div>

resources/views/response_comments/table.blade.php
<div class="table-responsive">
    <table class="table" id="responseComments-table">
        <thead>
            <tr>
                <th>Response Value</th>
        <th>Comment Id</th>
                <th colspan="3">Action</th>
            </tr>
        </thead>
        <tbody>
        @foreach($responseComments as $responseComment)
            <tr>
                <td>{{ $responseComment->response_value }}</td>
            <td>{{ $responseComment->comment_id }}</td>
                <td>
                    {!! Form::open(['route' => ['responseComments.destroy', $responseComment->id], 'method' => 'delete']) !!}
                    <div class='btn-group'>
                        <a href="{{ route('responseComments.show', [$responseComment->id]) }}" class='btn btn-default btn-xs'><i class="glyphicon glyphicon-eye-open"></i></a>
                        <a href="{{ route('responseComments.edit', [$responseComment->id]) }}" class='btn btn-default btn-xs'><i class="glyphicon glyphicon-edit"></i></a>
                        {!! Form::button('<i class="glyphicon glyphicon-trash"></i>', ['type' => 'submit', 'class' => 'btn btn-danger btn-xs', 'onclick' => "return confirm('Are you sure?')"]) !!}
                    </div>
                    {!! Form::close() !!}
                </td>
            </tr>
        @endforeach
        </tbody>
    </table>
</div>